<a href="https://colab.research.google.com/github/dufma9385/Python_machinelearning/blob/master/20_08_12_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 넘파이 사용하기
import numpy as np

In [ ]:
list1 = [1,3,5,7,9]
np1 = np.array( list1 )
list2 = [[1,2,3],[4,5,6]]
np2 = np.array(list2)

In [ ]:
print(list1)
print(np1)
print(list2)
np2

[1, 3, 5, 7, 9]
[1 3 5 7 9]
[[1, 2, 3], [4, 5, 6]]


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# list1 + 1 불가 for문 사용 필수
for i in list1:
  print(i+1,end=" ")

2 4 6 8 10 

In [ ]:
print(np1) #반복을 개발자가 할 필요 없다
np1 + 1

[1 3 5 7 9]


array([ 2,  4,  6,  8, 10])

In [ ]:
np1.ndim  #차원 수
np2.ndim  #3행 3열짜리
np.ndim(np2) #차원 수 반환 함수 -> np1.ndim
np1.shape #행,열,수
np2.shape
np1.size #항목갯수
np2.size
np1.dtype #데이터 타입
np2.dtype
#np2.astype("float64") #타입변환

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
print(list(range(1,5))) #1,2,3,4
print(np.arange(1,5))

[1, 2, 3, 4]
[1 2 3 4]


In [ ]:
np.random.randn(10) #0-1사이 정규분포 난수생성

array([-0.57675182,  1.6714283 , -0.55865586,  1.06192318,  1.64246059,
       -1.23492867,  0.73684604,  0.8542905 ,  0.63693692,  0.5471864 ])

In [ ]:
np1[1]=10
np1

array([ 1, 10,  5,  7,  9])

In [ ]:
np1 = np.array([[1,2],[3,4]])
np2 = np.array([[1,2],[3,4]])
print(np1)
print(np2)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [ ]:
np1+np2

array([[2, 4],
       [6, 8]])

In [ ]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
arr2 = np.array([arr[1,0], arr[1,1], arr[1,2]])
arr2

array([4, 5, 6])

In [ ]:
arr2[0] = 99 #복사본을 가져와서 적용하는것
arr2

array([99,  5,  6])

In [ ]:
arr #원본은 변하지 않는다

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
arr3 = arr[1:3, 1:3] #이상:미만
arr3

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
arr3[0,0] = 99 #8->99
arr3

array([[99,  9, 10]])

In [ ]:
bidx = arr >= 5
bidx

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
arr[bidx] # 결과값이 True인 항목만 추출, 1차원으로

array([ 5,  6,  7,  8,  9, 10, 11])

In [ ]:
arr[arr>=5]

array([ 5,  6,  7,  8,  9, 10, 11])

In [ ]:
# 참, 거짓 갯수를 행의 수만큼 넣기
arr[ [True, False,True] ]  #참에 해당하는 행만 추출

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [ ]:
scores=[
        #학년,반,번호,수학,영어,과학
        [1, 1, 1, 80, 70, 90],
        [1, 1, 2, 70, 70, 70],
        [2, 1, 1, 90, 80, 60],
        [2, 1, 2, 90, 80, 80],
]
score_np = np.array(scores)
score_np

array([[ 1,  1,  1, 80, 70, 90],
       [ 1,  1,  2, 70, 70, 70],
       [ 2,  1,  1, 90, 80, 60],
       [ 2,  1,  2, 90, 80, 80]])

In [ ]:
grades = score_np[:, 0] #학년 열
grades

array([1, 1, 2, 2])

In [ ]:
grades == 1 #1학년

array([ True,  True, False, False])

In [ ]:
score_np[ score_np[:, 0]==1] #1학년만

array([[ 1,  1,  1, 80, 70, 90],
       [ 1,  1,  2, 70, 70, 70]])

In [ ]:
score_np[0] #행
score_np[0:2] #슬라이싱 행(1학년만 추출)
score_np[0, ] #행추출, 열 생략 가능
# score_np[ ,0] #열추출, 행생략 불가
score_np[ : , [0,2]] #열추출, 행 생략 불가능
score_np[:, 0]==1 #1학년만 추출
score_np[ score_np[:,0]==1] #1학년 행 추출

array([1, 2, 1, 2])

In [ ]:
score_np

array([[ 1,  1,  1, 80, 70, 90],
       [ 1,  1,  2, 70, 70, 70],
       [ 2,  1,  1, 90, 80, 70],
       [ 2,  1,  2, 90, 80, 80]])

In [ ]:
bidx = score_np[:, 0]==1
np.where(bidx, "처리대상", "미처리")

array(['처리대상', '처리대상', '미처리', '미처리'], dtype='<U4')

In [ ]:
np.where(score_np[:,5]>=90,"A",
         np.where(score_np[:,5]>=80, "B",
                  np.where(score_np[:,5]>=70, "C","D")))

array(['A', 'C', 'D', 'B'], dtype='<U1')

In [ ]:
score_data = score_np[:, 3:]
score_data

array([[80, 70, 90],
       [70, 70, 70],
       [90, 80, 60],
       [90, 80, 80]])

In [ ]:
np.sum(score_data, axis=0) #행방향 처리
np.sum(score_data, axis=1) #열방향 처리
np.mean(score_data)
np.mean(score_data, axis=0) #행단위 처리 -> 열별합 
np.mean(score_data, axis=1) #열단위 처리-> 행별
np.min(score_data)
np.min(score_data, axis=0)
np.min(score_data, axis=1)
np.argmin(score_data, axis=0)
np.argmin(score_data, axis=1)

array([1, 0, 2, 1])

In [ ]:
arr6= np.arange(1,46)
arr6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [ ]:
np.random.shuffle(arr6) 
arr6

array([10, 39, 36, 20, 45, 23, 33, 44, 28, 34, 14,  9, 18, 13,  3,  1, 37,
        7, 41,  5, 11, 43, 35, 31, 12, 21,  2, 27, 15, 38, 26, 19,  8,  6,
        4, 25, 29, 16, 24, 42, 22, 30, 40, 17, 32])

In [ ]:
np.random.seed(100) #Pesudo Random
np.random.randint(1,46, 6) #6개
# np.random.randint(1,46,size=(2,3)) #2행3열

array([ 9, 25,  4, 40, 24, 16])

In [ ]:
import pandas as pd
s1 = pd.Series([70,80,90], index=['eng','math','sci'])
s1

eng     70
math    80
sci     90
dtype: int64

In [ ]:
s1[ ['math', 'eng']]
s1['math':] #'math'부터 끝까지 추출
s1[:'math'] #처음부터 'math'까지 추출

eng     70
math    80
dtype: int64

In [ ]:
o1 = pd.Series([4,5,-3,6], index=list("dacd"))
o1

d    4
a    5
c   -3
d    6
dtype: int64

In [ ]:
o1.index

Index(['d', 'a', 'c', 'd'], dtype='object')

In [ ]:
o1.values

array([ 4,  5, -3,  6])

In [ ]:
o1[ o1>0 ]

d    4
a    5
d    6
dtype: int64